version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      # - JWT_SECRET=your_jwt_secret
    volumes:
      - .:/app
      - /app/node_modules
